; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -march=sbf | FileCheck %s --check-prefix=CHECK
; RUN: llc < %s -march=sbf -mcpu=v3 -mattr=+alu32 | FileCheck %s --check-prefix=CHECK-ALU32

%struct.S = type { i32, i32, i32 }

@s = common global %struct.S zeroinitializer, align 4

; Function Attrs: nounwind readonly uwtable
define { i64, i32 } @bar(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) #0 {
; CHECK-LABEL: bar:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lddw r1, s
; CHECK-NEXT:    ldxdw r0, [r1 + 0]
; CHECK-NEXT:    ldxw r1, [r1 + 8]
; CHECK-NEXT:    exit
;
; CHECK-ALU32-LABEL: bar:
; CHECK-ALU32:       # %bb.0: # %entry
; CHECK-ALU32-NEXT:    lddw r1, s
; CHECK-ALU32-NEXT:    ldxdw r0, [r1 + 0]
; CHECK-ALU32-NEXT:    ldxw w1, [r1 + 8]
; CHECK-ALU32-NEXT:    exit
entry:
  %retval.sroa.0.0.copyload = load i64, i64* bitcast (%struct.S* @s to i64*), align 4
  %retval.sroa.2.0.copyload = load i32, i32* getelementptr inbounds (%struct.S, %struct.S* @s, i64 0, i32 2), align 4
  %.fca.0.insert = insertvalue { i64, i32 } undef, i64 %retval.sroa.0.0.copyload, 0
  %.fca.1.insert = insertvalue { i64, i32 } %.fca.0.insert, i32 %retval.sroa.2.0.copyload, 1
  ret { i64, i32 } %.fca.1.insert
}
